[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel"


[[mgr.prepend_keymap]]
on = "<C-w>"
run = "close"
desc = "Close current tab"


[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter directory or open file"


[[mgr.prepend_keymap]]
on = "<Right>"
run = "plugin smart-enter"
desc = "Enter directory or open file"


[[mgr.prepend_keymap]]
on = "2"
run = "plugin smart-switch 1"
desc = "Switch or create tab 2"


[[mgr.prepend_keymap]]
on = "3"
run = "plugin smart-switch 2"
desc = "Switch or create tab 3"


[[mgr.prepend_keymap]]
on = "4"
run = "plugin smart-switch 3"
desc = "Switch or create tab 4"


[[mgr.prepend_keymap]]
on = "5"
run = "plugin smart-switch 4"
desc = "Switch or create tab 5"


[[mgr.prepend_keymap]]
on = "<C-p>"
run = "plugin toggle-pane min-preview"
desc = "Toggle preview pane"


[[mgr.prepend_keymap]]
on = ["g", "g"]
run = "arrow top"
desc = "Go to top"


[[mgr.prepend_keymap]]
on = ["g", "<Space>"]
run = "cd --interactive"
desc = "Jump interactive"


[[mgr.prepend_keymap]]
on = ["g", "f"]
run = "follow"
desc = "Follow symlink"


[[mgr.append_keymap]]
on = ["g", "p"]
run = "cd ~/Pictures"
desc = "Go ~/Pictures"


[[mgr.append_keymap]]
on = ["g", "l"]
run = "cd ~/.local"
desc = "Go ~/.local"


[[mgr.append_keymap]]
on = ["g", "s"]
run = "cd /usr/share"
desc = "Go /usr/share"


[[mgr.append_keymap]]
on = ["g", "m"]
run = "cd /mnt"
desc = "Go /mnt"


[[mgr.append_keymap]]
on = ["g", "r"]
run = "cd /"
desc = "Go to root"


[[mgr.append_keymap]]
on = ["g", "t"]
run = "cd ~/.local/share/Trash/files"
desc = "Go to trash"


[[mgr.prepend_keymap]]
on = ["<C-h>"]
run = "hidden toggle"
desc = "Toggle hidden files"


[[mgr.prepend_keymap]]
on = ["<C-j>"]
run = "arrow 20%"
desc = "Dash down"


[[mgr.prepend_keymap]]
on = ["<C-k>"]
run = "arrow -20%"
desc = "Dash cursor up"
